#config for nginx
- name: replace string nginx
  replace:
    path: "{{ file4 }}"
    regexp: "{{ oldip|join(' ') }}"
    replace: "{{ myip|join(' ') }}"

- name: restart service nginx
  command: nginx -s reload