#config for MONITORIX
- name: replace string monitorix
  replace:
    path: "{{ file2 }}"
    regexp: "{{ oldip|join(' ') }}"
    replace: "{{ myip|join(' ') }}"
  notify: restart service monitorix



